---

- "*arr":
    - Sonarr:
        icon: sonarr.png
        href: "{{HOMEPAGE_VAR_SONARR_URL}}"
        description: TV Series Manager
        widget:
          type: sonarr
          url: "{{HOMEPAGE_VAR_SONARR_URL}}"
          key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
          enableQueue: true
    - Radarr:
        icon: radarr.png
        href: "{{HOMEPAGE_VAR_RADARR_URL}}"
        description: Movies Manager
        widget:
          type: radarr
          url: "{{HOMEPAGE_VAR_RADARR_URL}}"
          key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
          enableQueue: true
    - Prowlarr:
        icon: prowlarr.png
        href: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
        description: Indexers Manager
        widget:
          type: prowlarr
          url: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
          key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
    - Bazarr:
        icon: bazarr.png
        href: "{{HOMEPAGE_VAR_BAZARR_URL}}"
        description: Subtitles Manager
        widget:
          type: bazarr
          url: "{{HOMEPAGE_VAR_BAZARR_URL}}"
          key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"
- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: Media Server
        widget:
          type: jellyfin
          url: "{{HOMEPAGE_VAR_JELLYFIN_INTERNAL_URL}}"
          key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
          enableBlocks: true
          enableNowPlaying: true
          enableUser: true
          enableMediaControl: false
          showEpisodeNumber: true
          expandOneStreamToTwoRows: false
    - Jellyseerr:
        icon: jellyseerr.png
        href: "{{HOMEPAGE_VAR_JELLYSEERR_URL}}"
        description: Media Request Server
        server: raspberry-docker
        container: jellyseerr
        widget:
          type: jellyseerr
          url: "{{HOMEPAGE_VAR_JELLYSEERR_INTERNAL_URL}}"
          key: "{{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}"
    - Audiobookshelf:
        icon: audiobookshelf.png
        href: "{{HOMEPAGE_VAR_AUDIOBOOKSHELF_URL}}"
        description: Audiobooks Server
        server: raspberry-docker
        container: audiobookshelf
        widget:
          type: audiobookshelf
          url: "{{HOMEPAGE_VAR_AUDIOBOOKSHELF_INTERNAL_URL}}"
          key: "{{HOMEPAGE_VAR_AUDIOBOOKSHELF_API_KEY}}"
- Torrenting:
    - Autobrr:
        icon: autobrr.png
        href: "{{HOMEPAGE_VAR_AUTOBRR_URL}}"
        description: Auto Download Tool
        server: raspberry-docker
        container: autobrr
        widget:
          type: autobrr
          url: "{{HOMEPAGE_VAR_AUTOBRR_URL}}"
          key: "{{HOMEPAGE_VAR_AUTOBRR_API_KEY}}"
    - qui:
        icon: qui.png
        href: "{{HOMEPAGE_VAR_QBIT_URL}}"
        description: Web interface for qBittorrent
        server: raspberry-docker
        container: qui
        widget:
          type: qbittorrent
          url: "{{HOMEPAGE_VAR_QUI_URL}}"
          username: username
          password: password
          enableLeechProgress: true
          enableLeechSize: true
    - Transmission:
        icon: transmission.png
        href: "{{HOMEPAGE_VAR_TRANSMISSION_URL}}"
        description: Transmission Torrent Client
        widget:
          type: transmission
          url: "{{HOMEPAGE_VAR_TRANSMISSION_URL}}"
          username: "{{HOMEPAGE_VAR_TRANSMISSION_USERNAME}}"
          password: "{{HOMEPAGE_VAR_TRANSMISSION_PASS}}"
          rpcUrl: /transmission/
- Docker:
    - Portainer:
        icon: portainer-alt.png
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: Docker Containers Manager
        server: raspberry-docker
        container: portainer
        widget:
          type: portainer
          url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
          env: 11
          kubernetes: false
          key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"
    - Diun:
        icon: diun.png
        href: https://crazymax.dev/diun
        description: Docker Image Update Notifier
        server: raspberry-docker
        container: diun
    - Dozzle:
        icon: dozzle.png
        href: "{{HOMEPAGE_VAR_DOZZLE_URL}}"
        description: Docker log viewer
        server: raspberry-docker
        container: dozzle
- Networking:
    - PiHole:
        icon: pi-hole.png
        href: "{{HOMEPAGE_VAR_PIHOLE_WEB_URL}}"
        description: Network-wide Ad Blocker
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
          version: 6
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
    - Caddy:
        icon: caddy
        href: https://caddyserver.com
        description: Reverse Proxy
        server: raspberry-docker
        container: caddy
    - GoAccessPublic:
        icon: goaccess.png
        href: "{{HOMEPAGE_VAR_GOACCESS_PUBLIC_URL}}"
        description: Web log analyzer
        server: raspberry-docker
        container: goaccess-public
- Auth:
    - Authentik:
        icon: authentik.png
        href: "{{HOMEPAGE_VAR_AUTHENTIK_URL}}"
        description: Identity Provider (IdP) for modern SSO
        server: raspberry-docker
        container: authentik-server
        widget:
          type: authentik
          url: "{{HOMEPAGE_VAR_AUTHENTIK_INTERNAL_URL}}"
          key: "{{HOMEPAGE_VAR_AUTHENTIK_API_KEY}}"
          version: 2
    - Vaultwarden:
        icon: vaultwarden.png
        href: "{{HOMEPAGE_VAR_VAULTWARDEN_URL}}"
        description: Password Manager
        server: raspberry-docker
        container: vaultwarden
- Monitoring:
    - Beszel:
        icon: beszel.png
        href: "{{HOMEPAGE_VAR_BESZEL_URL}}"
        description: Server Monitoring
        server: raspberry-docker
        container: beszel
    - Notifiarr Web:
        icon: notifiarr.png
        href: "{{HOMEPAGE_VAR_NOTIFIARR_WEB_URL}}"
        description: Notifications Manager
    - Notifiarr Client:
        icon: notifiarr.png
        href: "{{HOMEPAGE_VAR_NOTIFIARR_CLIENT_URL}}"
        description: Notifiarr Client
- Homelab-1:
    - Homepage:
        icon: homepage.png
        href: https://gethomepage.dev
        description: "Homepage Docs"
    - "Jellyfin Docs":
        icon: jellyfin.png
        href: https://jellyfin.org/docs
        description: "Jellyfin Docs"
    - "Jellyseerr Docs":
        icon: jellyseerr.png
        href: https://docs.seerr.dev
        description: "Jellyseerr Docs"
    - "Audiobookshelf Docs":
        icon: audiobookshelf.png
        href: https://www.audiobookshelf.org/docs
        description: "Audiobookshelf Docs"
    - "Autobrr Docs":
        icon: autobrr.png
        href: https://autobrr.com/introduction
        description: "Autobrr Docs"
    - "Qui Docs":
        icon: qui.png
        href: https://getqui.com/docs/intro
        description: "Qui Docs"
    - "Cross-Seed Docs":
        icon: cross-seed.png
        href: https://www.cross-seed.org/docs/basics/getting-started
        description: "Cross-Seed Docs"
- Homelab-2:
    - "Radarr Docs":
        icon: radarr.png
        href: https://wiki.servarr.com/radarr
        description: "Radarr Docs"
    - "Sonarr Docs":
        icon: sonarr.png
        href: https://wiki.servarr.com/sonarr
        description: "Sonarr Docs"
    - "Prowlarr Docs":
        icon: prowlarr.png
        href: https://wiki.servarr.com/prowlarr
        description: "Prowlarr Docs"
    - "Bazarr Docs":
        icon: bazarr.png
        href: https://wiki.bazarr.media
        description: "Bazarr Docs"
    - "Notifiarr Docs":
        icon: notifiarr.png
        href: https://notifiarr.wiki
        description: "Notifiarr Docs"
    - "Authentik Docs":
        icon: authentik.png
        href: https://docs.goauthentik.io
        description: "Authentik Docs"
    - "Vaultwarden Docs":
        icon: vaultwarden.png
        href: https://github.com/dani-garcia/vaultwarden/wiki
        description: "Vaultwarden Docs"
- Homelab-3:
    - "Portainer Docs":
        icon: portainer-alt.png
        href: https://docs.portainer.io
        description: "Portainer Docs"
    - "Diun Docs":
        icon: diun.png
        href: https://crazymax.dev/diun
        description: "Diun Docs"
    - "Dozzle Docs":
        icon: dozzle.png
        href: https://dozzle.dev/guide/what-is-dozzle
        description: "Dozzle Docs"
    - "Beszel Docs":
        icon: beszel.png
        href: https://beszel.dev/guide/what-is-beszel
        description: "Beszel Docs"
    - "Caddy Docs":
        icon: caddy.png
        href: https://caddyserver.com/docs
        description: "Caddy Docs"
    - "PiHole Docs":
        icon: pi-hole.png
        href: https://docs.pi-hole.net
        description: "Pi-Hole Docs"
- Homelab-4:
    - "Selfh.st":
        icon: selfh-st.png
        href: https://selfh.st
        description: "Self Host Apps Info"
    - "XDA-Devs":
        icon: si-xdadevelopers
        href: https://www.xda-developers.com/
        description: "Hardware & Self Host"
    - "Trash Guides":
        icon: https://trash-guides.info/img/logo.png
        href: https://trash-guides.info
        description: "Guides that aren't trash"
    - Kodi:
        icon: kodi.png
        href: https://kodi.tv/download/android
        description: "Open Source Home Theater Software"