---

title: Jeliozver Homepage
theme: dark
color: slate
useEqualHeights: true
fullWidth: false
statusStyle: "dot"

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

layout:
  Starr Apps:
    icon: servarr.png
    header: true
    style: row
    columns: 4
  Media Apps:
    icon: mdi-play-network-#FFFFFF
    header: true
    style: row
    columns: 3
  Torrenting:
    icon: yarr.png
    header: true
    style: row
    columns: 3
  Networking:
    icon: mdi-network-#FFFFFF
    header: true
    style: row
    columns: 4
  Auth:
    icon: mdi-shield-lock-#FFFFFF
    header: true
    style: row
    columns: 2
  Monitoring:
    icon: mdi-monitor-eye-#FFFFFF
    header: true
    style: row
    columns: 4
