---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Jeliozver Homepage
theme: dark
color: slate
useEqualHeights: true
fullWidth: false
statusStyle: "dot"

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

layout:
  Starr Apps:
    header: true
    style: row
    columns: 4
  Media Apps:
    header: true
    style: row
    columns: 3
  Torrenting:
    header: true
    style: row
    columns: 3
  Networking:
    header: true
    style: row
    columns: 3
  Auth:
    header: true
    style: row
    columns: 2
  Notifications:
    header: true
    style: row
    columns: 2